---
  - name: Tomcat install and configure Play 1
    hosts: nodes
    gather_facts: true
    vars:
      - java_version: 1.8.0
      - tomcat_version: 9.0.69
      - tomcat_bundle_url: https://dlcdn.apache.org/tomcat/tomcat-{{tomcat_version.split('.')[0]}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
      - tomcat_port: 80
    tasks:
      - name: ping test
        ping:

      - block:
        - name: Update {{ansible_distribution}}/{{ansible_os_family}} server
          yum:
            name: '*'
            state: latest
        - name: Java version {{java_version}} openjdk installation
          yum:
            name: java-{{java_version}}-openjdk
            state: present
        - name: Configuring the default Java version
          alternatives:
            name: java
            link: /usr/bin/java
            path: /usr/lib/jvm/jre-{{java_version}}-openjdk/bin/java
        become: yes

      - block:
        - name: Tomcat shutdown script file check
          stat:
            path: /opt/apache-tomcat-9.0.69/bin/shutdown.sh
          register: shutdown_script
        - name: Stop Tomcat service
          command: /opt/apache-tomcat-9.0.69/bin/shutdown.sh
          delegate_to: '{{ansible_host}}'
          when: shutdown_script.stat.exists
        - name: Download Tomcat binaries
          get_url: 
            url: '{{tomcat_bundle_url}}'
            dest: /opt
        - name: Unarchive Tomcat binaries
          unarchive:
            src: /opt/apache-tomcat-{{tomcat_version}}.tar.gz
            dest: /opt
            remote_src: true
      # - name: Get Tomcat server.xml file
      #   fetch:
      #     src: /opt/apache-tomcat-9.0.69/conf/server.xml
      #     dest: server.xml.j2
      #     flat: yes
      #   become: yes
      #   run_once: yes
        - name: Change port
          template:
            src: server.xml.j2
            dest: /opt/apache-tomcat-{{tomcat_version}}/conf/server.xml
        - name: Start Tomcat service
          command: nohup /opt/apache-tomcat-9.0.69/bin/startup.sh &
          delegate_to: '{{ansible_host}}'
        become: yes


